<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function getAvecTags(array $tags)
	{
		$qb = $this->createQueryBuilder('a');
		
		$qb ->join('a.tags', 't')
			->where($qb->expr()->in('t.nom', $tags));
		
		return $qb->getQuery()->getResult();
	}
}