parameters:
#    sdz_user.example.class: Sdz\UserBundle\Example

services:
    sdz_user.registration.form.type:
        class: Sdz\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cp_user_registration }
