security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager
    firewalls:
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /sdz/login
                use_forward:    false
                check_path:     /sdz/login_check
                failure_path:   null
                default_target_path: /blog
            logout:
                path:   /sdz/logout
                target: /blog
            anonymous:    true

    role_hierarchy:
        ROLE_ADMIN:      ROLE_USER
        ROLE_SUPERADMIN: ROLE_ADMIN
    access_control:
        # Liste des pages accessibles à tous les utilisateurs (ne pas toucher)
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resseting$, role: IS_AUTHENTICATED_ANONYMOUSLY }security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager
    firewalls:
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /sdz/login
                use_forward:    false
                check_path:     /sdz/login_check
                failure_path:   null
                default_target_path: /blog
            logout:
                path:   /sdz/logout
                target: /blog
            anonymous:    true

    role_hierarchy:
        ROLE_ADMIN:      ROLE_USER
        ROLE_SUPERADMIN: ROLE_ADMIN
    access_control:
        # Liste des pages accessibles à tous les utilisateurs (ne pas toucher)
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resseting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
        - { path: ^/admin/, role: ROLE_ADMIN }
        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
        - { path: ^/sdz/change-password, role: ROLE_USER }
        - { path: ^/blog/article/crud/, role: ROLE_USER }
        # PAGES ACCESSIBLES À TOUS
        - { path: ^/blog.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
        - { path: ^/admin/, role: ROLE_ADMIN }
        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
        - { path: ^/sdz/change-password, role: ROLE_USER }
        # PAGES ACCESSIBLES À TOUS
        - { path: ^/blog.*, role: IS_AUTHENTICATED_ANONYMOUSLY }