<?php

namespace Sdz\SitesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    
	public function getByUser($user, $deleted = false)
	{
		$qb = $this->createQueryBuilder('s')
                        ->join('s.User', 'u');
                
                $qb->where('u = :user')
                        ->setParameter('user', $user)
                   ->andWhere('s.deleted = :deleted')
                        ->setParameter('deleted', $deleted);
			
		return $qb->getQuery()->getResult();
	}
        
        public function getSite($user, $url)
        {
            $qb = $this->createQueryBuilder('s');
            
            $qb->where('s.User = :user')
                    ->setParameter('user', $user)
               ->andWhere('s.url = :url')
                    ->setParameter('url', $url);
            
            return $qb->getQuery()->getSingleResult();
        }
	
}